

# Configuration spécifique pour la Suisse
# Support multi-langue (FR/DE/IT) - Pas de DataViz
# Commande: DEPLOY_COUNTRY=CH docker-compose -f docker-compose.yaml -f docker-compose.ch.yaml --profile ch up -d

services:
  django:
    environment:
      # Configuration Suisse spécifique
      - DEPLOY_COUNTRY=CH
      - DJANGO_ALLOWED_HOSTS=ch.pandemic-predictions.org,localhost,127.0.0.1
      # Multi-langue
      - CH_LANGUAGES=fr,de,it
      - CH_DEFAULT_LANGUAGE=fr
      - DJANGO_LANGUAGE_CODE=fr-ch
      - DJANGO_TIME_ZONE=Europe/Zurich
      # Désactivation DataViz
      - CH_DISABLE_DATAVIZ=true
      - CH_DISABLE_METABASE=true
      # Support des langues officielles suisses
      - SUPPORTED_LANGUAGES=fr,de,it
      - USE_I18N=true
      - USE_L10N=true
      - LOCALE_PATHS=/django_api/locale
    labels:
      - "country=CH"
      - "multi-language=enabled"
      - "dataviz=disabled"

  frontend:
    environment:
      # Interface multi-langue Suisse
      - DEPLOY_COUNTRY=CH
      - FRONTEND_LANGUAGE=fr
      - REACT_APP_MULTI_LANGUAGE=true
      - REACT_APP_SUPPORTED_LANGUAGES=fr,de,it
      - REACT_APP_DEFAULT_LANGUAGE=fr
      - REACT_APP_API_URL=http://localhost:8001
      # Désactivation du DataViz
      - REACT_APP_DATAVIZ_ENABLED=false
      - REACT_APP_METABASE_ENABLED=false
    labels:
      - "country=CH"
      - "languages=fr,de,it"

  airflow-webserver:
    environment:
      # Configuration Airflow pour la Suisse
      - DEPLOY_COUNTRY=CH
      - AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE=Europe/Zurich
      - AIRFLOW__CORE__DEFAULT_TIMEZONE=Europe/Zurich
      # Multi-langue
      - AIRFLOW_LANGUAGE=fr
    labels:
      - "country=CH"

  airflow-scheduler:
    environment:
      - DEPLOY_COUNTRY=CH
      - AIRFLOW__CORE__DEFAULT_TIMEZONE=Europe/Zurich
    labels:
      - "country=CH"

  postgres:
    environment:
      # Configuration base de données Suisse
      - TZ=Europe/Zurich
      - POSTGRES_INITDB_ARGS=--locale=fr_CH.UTF-8
    labels:
      - "country=CH"
      - "timezone=Europe/Zurich"

  # Service de traduction multi-langue (spécifique Suisse)
  translation-service:
    image: python:3.9-slim
    container_name: translation_service_ch
    networks:
      - airflow-net-v2
    profiles:
      - ch
    environment:
      - DEPLOY_COUNTRY=CH
      - SUPPORTED_LANGUAGES=fr,de,it
      - DEFAULT_LANGUAGE=fr
    volumes:
      - ./translations:/app/translations
      - ./scripts:/opt/scripts
    working_dir: /app
    command: >
      sh -c "echo 'Service de traduction démarré pour la Suisse' &&
             echo 'Langues supportées: FR, DE, IT' &&
             echo 'Mode simulation actif' &&
             while true; do
               echo '[$(date)] Service de traduction actif - Langues: FR, DE, IT'
               sleep 3600
             done"
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "echo", "healthy"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 60s
    labels:
      - "service=translation"
      - "country=CH"
      - "languages=fr,de,it"

  # Service de gestion des langues (spécifique Suisse)
  language-manager:
    image: alpine:latest
    container_name: language_manager_ch
    networks:
      - airflow-net-v2
    profiles:
      - ch
    environment:
      - DEPLOY_COUNTRY=CH
      - LANGUAGES=fr,de,it
      - DEFAULT_LANGUAGE=fr
    volumes:
      - ./translations:/var/translations
      - ./logs:/var/log/languages
    command: >
      sh -c "echo 'Gestionnaire de langues démarré pour la Suisse' &&
             echo 'Configuration:' &&
             echo '- Français (FR): Langue par défaut' &&
             echo '- Allemand (DE): Langue secondaire' &&
             echo '- Italien (IT): Langue tertiaire' &&
             mkdir -p /var/translations/{fr,de,it} &&
             while true; do
               echo '[$(date)] Vérification des fichiers de traduction...'
               ls -la /var/translations/
               sleep 3600
             done"
    labels:
      - "service=language-manager"
      - "country=CH"

# Note: Pas de service Metabase pour la Suisse
# conformément aux spécifications MSPR 3 (DataViz désactivé)

