# Generated by Django 5.1.5 on 2025-02-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoronaReport',
            fields=[
                ('date', models.TextField(primary_key=True, serialize=False)),
                ('country', models.TextField()),
                ('cumulative_total_cases', models.FloatField()),
                ('daily_new_cases', models.FloatField(blank=True, null=True)),
                ('active_cases', models.FloatField(blank=True, null=True)),
                ('cumulative_total_deaths', models.FloatField()),
                ('daily_new_deaths', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'corona_report',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CovidGlobal',
            fields=[
                ('country', models.TextField(db_column='Country/Region', primary_key=True, serialize=False)),
                ('confirmed', models.BigIntegerField(blank=True, db_column='Confirmed', null=True)),
                ('deaths', models.BigIntegerField(blank=True, db_column='Deaths', null=True)),
                ('recovered', models.BigIntegerField(blank=True, db_column='Recovered', null=True)),
                ('active', models.BigIntegerField(blank=True, db_column='Active', null=True)),
                ('new_cases', models.BigIntegerField(blank=True, db_column='New cases', null=True)),
                ('new_deaths', models.BigIntegerField(blank=True, db_column='New deaths', null=True)),
                ('new_recovered', models.BigIntegerField(blank=True, db_column='New recovered', null=True)),
                ('deaths_100_cases', models.FloatField(blank=True, db_column='Deaths / 100 Cases', null=True)),
                ('recovered_100_cases', models.FloatField(blank=True, db_column='Recovered / 100 Cases', null=True)),
                ('deaths_100_recovered', models.FloatField(blank=True, db_column='Deaths / 100 Recovered', null=True)),
                ('confirmed_last_week', models.BigIntegerField(blank=True, db_column='Confirmed last week', null=True)),
                ('one_week_change', models.BigIntegerField(blank=True, db_column='1 week change', null=True)),
                ('one_week_percent_increase', models.FloatField(blank=True, db_column='1 week % increase', null=True)),
                ('who_region', models.TextField(blank=True, db_column='WHO Region', null=True)),
            ],
            options={
                'db_table': 'covid_global',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Monkeypox',
            fields=[
                ('location', models.TextField(primary_key=True, serialize=False)),
                ('iso_code', models.TextField()),
                ('date', models.TextField()),
                ('total_cases', models.FloatField()),
                ('total_deaths', models.FloatField(blank=True, null=True)),
                ('new_cases', models.FloatField(blank=True, null=True)),
                ('new_deaths', models.FloatField(blank=True, null=True)),
                ('new_cases_smoothed', models.FloatField(blank=True, null=True)),
                ('new_deaths_smoothed', models.FloatField(blank=True, null=True)),
                ('new_cases_per_million', models.FloatField(blank=True, null=True)),
                ('total_cases_per_million', models.FloatField(blank=True, null=True)),
                ('new_cases_smoothed_per_million', models.FloatField(blank=True, null=True)),
                ('new_deaths_per_million', models.FloatField(blank=True, null=True)),
                ('total_deaths_per_million', models.FloatField(blank=True, null=True)),
                ('new_deaths_smoothed_per_million', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'monkeypox',
                'managed': False,
            },
        ),
    ]
