# Generated by Django 5.1.5 on 2025-05-09 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CovidData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('total_cases', models.IntegerField()),
                ('daily_cases', models.IntegerField()),
                ('active_cases', models.IntegerField()),
                ('total_deaths', models.IntegerField()),
                ('daily_deaths', models.IntegerField()),
            ],
            options={
                'db_table': 'worldometer_coronavirus_daily_data',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('iso_code', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelMetrics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model_type', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('mse', models.FloatField()),
                ('rmse', models.FloatField()),
                ('mae', models.FloatField()),
                ('r2_score', models.FloatField()),
                ('cv_rmse', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MonkeyPoxData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('total_cases', models.IntegerField()),
                ('daily_cases', models.IntegerField()),
                ('total_deaths', models.IntegerField()),
                ('daily_deaths', models.IntegerField()),
            ],
            options={
                'db_table': 'owid_monkeypox_data',
            },
        ),
        migrations.CreateModel(
            name='Virus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('prediction_date', models.DateField()),
                ('transmission_rate', models.FloatField(blank=True, null=True)),
                ('mortality_rate', models.FloatField(blank=True, null=True)),
                ('predicted_cases', models.IntegerField(blank=True, null=True)),
                ('predicted_deaths', models.IntegerField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pandemics_app.location')),
                ('virus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pandemics_app.virus')),
            ],
            options={
                'ordering': ['-prediction_date'],
            },
        ),
        migrations.CreateModel(
            name='GeographicalSpreadPrediction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('prediction_date', models.DateField()),
                ('predicted_new_locations', models.IntegerField()),
                ('virus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pandemics_app.virus')),
            ],
            options={
                'ordering': ['-prediction_date'],
            },
        ),
        migrations.CreateModel(
            name='Worldmeter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('total_cases', models.IntegerField(blank=True, null=True)),
                ('total_deaths', models.IntegerField(blank=True, null=True)),
                ('new_cases', models.IntegerField(blank=True, null=True)),
                ('new_deaths', models.IntegerField(blank=True, null=True)),
                ('new_cases_smoothed', models.IntegerField(blank=True, null=True)),
                ('new_deaths_smoothed', models.IntegerField(blank=True, null=True)),
                ('new_cases_per_million', models.IntegerField(blank=True, null=True)),
                ('total_cases_per_million', models.IntegerField(blank=True, null=True)),
                ('new_cases_smoothed_per_million', models.IntegerField(blank=True, null=True)),
                ('new_deaths_per_million', models.IntegerField(blank=True, null=True)),
                ('total_deaths_per_million', models.IntegerField(blank=True, null=True)),
                ('new_deaths_smoothed_per_million', models.IntegerField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pandemics_app.location')),
                ('virus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pandemics_app.virus')),
            ],
        ),
    ]
