# Generated by Django 5.1.5 on 2025-02-26 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pandemics_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coronareport',
            options={},
        ),
    ]
