# Generated by Django 5.1.5 on 2025-05-13 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pandemics_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='location',
            table='pandemics.location',
        ),
    ]
