# Generated by Django 5.1.5 on 2025-05-14 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pandemics_app", "0002_alter_location_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="location",
            options={"managed": False},
        ),
    ]
