# Generated by Django 5.1.5 on 2025-06-10 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pandemics_app', '0003_alter_location_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='virus',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='worldmeter',
            options={'managed': False},
        ),
    ]
